### ISSUE TITLE
3.9.2 is out

### ISSUE THREAD

**Issue by CanonCan** [malvarez00/Docker-UniFi-Video#1]
Hello @malvarez00 not really an issue to report but I see 3.9.2 is out any plans to convert this to a docker update?

**Comment by malvarez00** [comment]
I’ll do a test and check for an update

Miguel Alvarez
(402) 429-3207

**Comment by CanonCan** [comment]
Awesome thanks !

**Comment by CanonCan** [comment]
thanks for the update......sadly now i too am having the issues everyone else is....super choppy video playback on live and in recordings...i hope its just the firmware and Ubiquiti can fix that soon

**Comment by CanonCan** [comment]
@malvarez00 do you know if there is a way to downgrade to the old docker? or can you post it as a separate one? I'd like to downgrade to remove this choppy live video i have

**Comment by CanonCan** [comment]
@malvarez00 Hi Miguel...Ubiquiti has confirmed 3.9.3 will be out soon to patch the choppy video issue found on 3.9.2

here is the thread

https://community.ubnt.com/t5/UniFi-Video/Choppy-live-playback-after-3-9-2-update/m-p/2258978#M98086

**Comment by malvarez00** [comment]
Those are good news

malvarez00

**Comment by CanonCan** [comment]
well not sure why it started happening but started getting "upgrading" on your docker container it just stuck there for over 10min

**Comment by CanonCan** [comment]
Hello @malvarez00 Just saw a post. 3.9.3 should be out next week please keep an eye our or if you prefer i'll let you know...

https://community.ubnt.com/t5/UniFi-Video/3-9-2-NVR-Offline-ERROR-Unable-to-connect-to-cloud-cannot/m-p/2263674#M98426

this should resolves the choppy video when viewing from a local browser and two should fix the disconnect from the cloud that errors out

**Comment by CanonCan** [comment]
@malvarez00 3.9.3 is out if you could please update the docker when you have a chance. this fixes the choppy live video over a web browser

**Comment by CanonCan** [comment]
@malvarez00 from what i can see the only thing you need is the firmware link...here you go

https://dl.ubnt.com/firmwares/ufv/v3.9.3/unifi-video.Ubuntu16.04_amd64.v3.9.3.deb

**Comment by CanonCan** [comment]
hello I updated the link for the controller software
[Docker-UniFi-Video-master3.9.3.zip](https://github.com/malvarez00/Docker-UniFi-Video/files/1783121/Docker-UniFi-Video-master3.9.3.zip)

**Comment by CanonCan** [comment]
I see the update done thank you!
